/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScorecardsRouteImport } from './routes/scorecards'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as AudiosRouteImport } from './routes/audios'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as TeamAgentNameRouteImport } from './routes/team.$agentName'
import { Route as CallsCallIdRouteImport } from './routes/calls.$callId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardsRoute = ScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiosRoute = AudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAgentNameRoute = TeamAgentNameRouteImport.update({
  id: '/team/$agentName',
  path: '/team/$agentName',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsCallIdRoute = CallsCallIdRouteImport.update({
  id: '/calls/$callId',
  path: '/calls/$callId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/audios': typeof AudiosRoute
  '/coaching': typeof CoachingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relatorios': typeof RelatoriosRoute
  '/scorecards': typeof ScorecardsRoute
  '/settings': typeof SettingsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/team/$agentName': typeof TeamAgentNameRoute
  '/calls/': typeof CallsIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/audios': typeof AudiosRoute
  '/coaching': typeof CoachingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relatorios': typeof RelatoriosRoute
  '/scorecards': typeof ScorecardsRoute
  '/settings': typeof SettingsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/team/$agentName': typeof TeamAgentNameRoute
  '/calls': typeof CallsIndexRoute
  '/team': typeof TeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/audios': typeof AudiosRoute
  '/coaching': typeof CoachingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/relatorios': typeof RelatoriosRoute
  '/scorecards': typeof ScorecardsRoute
  '/settings': typeof SettingsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/team/$agentName': typeof TeamAgentNameRoute
  '/calls/': typeof CallsIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/audios'
    | '/coaching'
    | '/dashboard'
    | '/login'
    | '/monitoring'
    | '/relatorios'
    | '/scorecards'
    | '/settings'
    | '/calls/$callId'
    | '/team/$agentName'
    | '/calls/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/audios'
    | '/coaching'
    | '/dashboard'
    | '/login'
    | '/monitoring'
    | '/relatorios'
    | '/scorecards'
    | '/settings'
    | '/calls/$callId'
    | '/team/$agentName'
    | '/calls'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/audios'
    | '/coaching'
    | '/dashboard'
    | '/login'
    | '/monitoring'
    | '/relatorios'
    | '/scorecards'
    | '/settings'
    | '/calls/$callId'
    | '/team/$agentName'
    | '/calls/'
    | '/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AudiosRoute: typeof AudiosRoute
  CoachingRoute: typeof CoachingRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ScorecardsRoute: typeof ScorecardsRoute
  SettingsRoute: typeof SettingsRoute
  CallsCallIdRoute: typeof CallsCallIdRoute
  TeamAgentNameRoute: typeof TeamAgentNameRoute
  CallsIndexRoute: typeof CallsIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecards': {
      id: '/scorecards'
      path: '/scorecards'
      fullPath: '/scorecards'
      preLoaderRoute: typeof ScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audios': {
      id: '/audios'
      path: '/audios'
      fullPath: '/audios'
      preLoaderRoute: typeof AudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$agentName': {
      id: '/team/$agentName'
      path: '/team/$agentName'
      fullPath: '/team/$agentName'
      preLoaderRoute: typeof TeamAgentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$callId': {
      id: '/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof CallsCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AudiosRoute: AudiosRoute,
  CoachingRoute: CoachingRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  RelatoriosRoute: RelatoriosRoute,
  ScorecardsRoute: ScorecardsRoute,
  SettingsRoute: SettingsRoute,
  CallsCallIdRoute: CallsCallIdRoute,
  TeamAgentNameRoute: TeamAgentNameRoute,
  CallsIndexRoute: CallsIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
