/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analyze': typeof AnalyzeRoute
  '/calls': typeof CallsRoute
  '/dashboard': typeof DashboardRoute
  '/monitoring': typeof MonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analyze': typeof AnalyzeRoute
  '/calls': typeof CallsRoute
  '/dashboard': typeof DashboardRoute
  '/monitoring': typeof MonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analyze': typeof AnalyzeRoute
  '/calls': typeof CallsRoute
  '/dashboard': typeof DashboardRoute
  '/monitoring': typeof MonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analyze'
    | '/calls'
    | '/dashboard'
    | '/monitoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/analyze' | '/calls' | '/dashboard' | '/monitoring'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analyze'
    | '/calls'
    | '/dashboard'
    | '/monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CallsRoute: typeof CallsRoute
  DashboardRoute: typeof DashboardRoute
  MonitoringRoute: typeof MonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyzeRoute: AnalyzeRoute,
  CallsRoute: CallsRoute,
  DashboardRoute: DashboardRoute,
  MonitoringRoute: MonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
